// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIiTJ3MI90cptlPKHkwZ_uYqfTqDUyftU',
    appId: '1:571688300079:web:7bbd7634c7328b0d29e0da',
    messagingSenderId: '571688300079',
    projectId: 'vara-hobe-v1',
    authDomain: 'vara-hobe-v1.firebaseapp.com',
    storageBucket: 'vara-hobe-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8lR7_2FOHriN9i0PO_Qbx_PTowRJ9VwM',
    appId: '1:571688300079:android:0fbc402d408b536029e0da',
    messagingSenderId: '571688300079',
    projectId: 'vara-hobe-v1',
    storageBucket: 'vara-hobe-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEIszdYQ2BAv3o9Y3eVq5IgFOpy4Y8TrE',
    appId: '1:571688300079:ios:8726f85900052d2e29e0da',
    messagingSenderId: '571688300079',
    projectId: 'vara-hobe-v1',
    storageBucket: 'vara-hobe-v1.appspot.com',
    iosBundleId: 'com.example.vharaHobeV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEIszdYQ2BAv3o9Y3eVq5IgFOpy4Y8TrE',
    appId: '1:571688300079:ios:8726f85900052d2e29e0da',
    messagingSenderId: '571688300079',
    projectId: 'vara-hobe-v1',
    storageBucket: 'vara-hobe-v1.appspot.com',
    iosBundleId: 'com.example.vharaHobeV1',
  );
}
